### PR TITLE
[#581] Update the Tuist to the latest version

### LINKED ISSUE #579: Fix: iOS Build Fails on GitHub Actions — Passed Invalid Params to `update_code_signing_settings`
## Issue

During the iOS build process on GitHub Actions, the workflow fails due to passing invalid parameters to 'update_code_signing_settings' when setting value  './TemplateApp.xcodeproj' for option 'path':
The log shows the following error messages:

```
[02:36:23]: Error setting value './TemplateApp.xcodeproj' for option 'path'
[02:36:23]: You passed invalid parameters to 'update_code_signing_settings'.
[02:36:23]: Check out the error below and available options by running `fastlane action update_code_signing_settings`
```

Failed run reference: https://github.com/nimblehq/ios-templates/actions/runs/18767826838/job/53546213379 ℹ️ 

## Expected

The GitHub Actions workflow should successfully set valid parameters and complete the iOS build without errors.
 
## Steps to reproduce

1. Trigger the iOS build workflow on GitHub Actions.
2. Wait for the fastlane gym or signing step to execute.
3. Observe the failure log showing “You passed invalid parameters to 'update_code_signing_settings'.”

### LINKED ISSUE #581: Update the Tuist to the latest version
## Why

Our iOS template is using an outdated Tuist version 3.2.0 while the latest is [4.104.6](https://github.com/tuist/tuist/releases/tag/4.104.6). This update is to ensure the stability of the template and allowing us to use new features of Tuist
 
## Who Benefits?

iOS chapter.

### PR DESCRIPTION
**Pull request by ducbm051291**
- Close #581
- Close #579 

## What happened 👀

This PR represents a major architectural overhaul of the iOS Template. It migrates the tooling from Tuist 3 to **Tuist 4**, completely removes **CocoaPods** in favor of **Swift Package Manager (SPM)**, and deprecates the **UIKit** interface to focus exclusively on **SwiftUI**.

**Key Changes:**

* **Tuist 4 Migration:** Updated `.tuist-version` to `4.110.3` and refactored `Project.swift` to use the latest `ProjectDescription` syntax.
* **Dependency Management:**
    * Removed `Podfile` and CocoaPods integration.
    * Introduced `Package.swift` to manage dependencies (Alamofire, Kingfisher, Firebase, etc.) via SPM.
    * Updated `Arkana` configuration to use SPM logic.
* **Interface:**
    * Deleted all `UIKit` templates, ViewControllers, and Storyboard logic.
    * Refactored the `iOSTemplateMaker` script to default to SwiftUI and remove the interface selection prompt.
* **CI/CD:**
    * Updated GitHub Actions versions (`checkout@v6`, `cache@v4`) to support Node 20.
    * Removed `pod install` steps from workflows (Bitrise, CodeMagic, GitHub Actions).
    * Added caching strategies for `.build` (SPM) directories.
* **Cleanup:** Removed unused scripts (`test_uikit_install_script`), extensions, and helpers related to the legacy setup.

## Insight 📝

**Why this solution?**
The iOS ecosystem has shifted significantly. UIKit is now considered legacy for new greenfield projects, and CocoaPods is in maintenance mode. By moving to a **SwiftUI + SPM + Tuist 4** stack, we ensure the template generates modern, future-proof projects that are faster to build and easier to maintain.

**Architecture Shift:**
Previously, Tuist generated a project that relied on a separate `pod install` step to link binary frameworks. Now, Tuist manages the SPM graph directly, integrating dependencies as native targets within the Xcode project structure.

**Refactoring Highlights:**
* **`Project.swift`**: Now defines dependencies using `.package(url: ...)` syntax.
* **`Fastlane`**: Updated to invoke tools like `xcbeautify` directly from the local environment or Mint/SPM, rather than relying on a Pod-installed binary.

## Proof Of Work 📹

Screenshot 2025-12-03 at 14 07 36

**Test upload build to firebase successfully now** [Result](https://github.com/nimblehq/ios-templates/actions/runs/19888761919)

Screenshot 2025-12-03 at 16 42 15

## Summary by CodeRabbit

* **New Features**
  * Template is SwiftUI-only, generates an .xcodeproj via Tuist and adopts Swift Package Manager with a package manifest.

* **Documentation**
  * CI and docs updated to reflect SPM/Tuist flows, .xcodeproj examples, and raised Xcode/Tuist requirements; tooling pinned for reproducible setups.

* **Chores**
  * Removed CocoaPods and Pod caches/configs, legacy UIKit template CI workflows, and Crashlytics symbol upload steps.

* **Improvements**
  * Expanded Firebase App Distribution APIs and added build/test debug logging.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: fastlane/Constants/Constant.swift [hunk 1]
```diff
@@ -73,11 +73,11 @@ enum Constant {
 
     static let stagingBundleId = "{BUNDLE_ID_STAGING}"
     static let productionBundleId = "{BUNDLE_ID_PRODUCTION}"
-    static let projectName = "{PROJECT_NAME}"
+    static let projectName = "{PROJECT_NAME}"
```
Comment (phongvhd93) [inline fastlane/Constants/Constant.swift]: Please remove the trailing spaces here

File: .tuist-version [hunk 2]
```diff
@@ -1 +1 @@
-3.2.0
\ No newline at end of file
+4.110.3
```
Comment (phongvhd93) [inline .tuist-version]: As we use mise do we still need this to manage the version of Tuist?

File: Tuist/ProjectDescriptionHelpers/Module.swift
Comment (phongvhd93) [inline Tuist/ProjectDescriptionHelpers/Module.swift]: Why was this removed? As we agreed to make `Data` and `Domain` before.

File: Package.swift [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+        
+        // Storage
+        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", from: "4.2.0"),
+        
+        // Tools
+        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", from: "10.0.0"),
+        .package(url: "https://github.com/nimblehq/NimbleExtension.git", branch: "master"),
+        // Note: R.swift is a code generation tool, not a library dependency
+        // .package(url: "https://github.com/mac-cain13/R.swift.git", from: "7.0.0"),
+        .package(url: "https://github.com/hmlongco/Factory.git", from: "2.0.0"),
```
Comment (phongvhd93) [inline Package.swift]: Let's take this chance to upgrade all the libs to the latest version 🚀

File: Package.swift [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+        .package(url: "https://github.com/nimblehq/NimbleExtension.git", branch: "master"),
+        // Note: R.swift is a code generation tool, not a library dependency
+        // .package(url: "https://github.com/mac-cain13/R.swift.git", from: "7.0.0"),
+        .package(url: "https://github.com/hmlongco/Factory.git", from: "2.3.0"),
+        
+        // Testing
+        .package(url: "https://github.com/Quick/Quick.git", from: "7.4.0"),
+        .package(url: "https://github.com/Quick/Nimble.git", from: "13.0.0"),
+        .package(url: "https://github.com/AliSoftware/OHHTTPStubs.git", from: "9.1.0"), // Provides OHHTTPStubsSwift product
+    ]
```
[the remark this answers is not in the document]
Comment (phongvhd93) [reply Package.swift]: We still have outdated 3rd parties, let's update them.

File: Tuist/ProjectDescriptionHelpers/Module.swift [hunk 5]
```diff
@@ -13,11 +6,10 @@ public enum Module: CaseIterable {
     case data
 
     public var name: String {
+
```
Comment (dquangit) [inline Tuist/ProjectDescriptionHelpers/Module.swift]: Please remove the blank space

File: Tuist/ProjectDescriptionHelpers/Module.swift [hunk 6]
```diff
@@ -13,11 +6,10 @@ public enum Module: CaseIterable {
...
         switch self {
-        case .domain:
-            return "Domain"
-        case .data:
-            return "Data"
+        case .domain: return "Domain"
+        case .data: return "Data"
```
Comment (dquangit) [inline Tuist/ProjectDescriptionHelpers/Module.swift]: Please omit `return`

File: Tuist/ProjectDescriptionHelpers/Module.swift [hunk 7]
```diff
@@ -48,16 +44,16 @@ public enum Module: CaseIterable {
...
-            "\(frameworkPath)/\(Constant.testsPath)/\(Constant.resourcesPath)/**"
+            "\(frameworkPath)/\(Constant.testsPath)/\(Constant.resourcesPath)/**",
+            "\(frameworkPath)/\(Constant.testsPath)/**/.gitkeep"
         ]
     }
 
-    public func getBundleId(mainBundleId: String) -> String {
-        "\(mainBundleId).\(name)"
+    public func bundleId(mainBundleId: String) -> String {
+        "\(mainBundleId).\(name.lowercased())"
```
Comment (dquangit) [inline Tuist/ProjectDescriptionHelpers/Module.swift]: Regarding [Apple documentation](https://developer.apple.com/documentation/bundleresources/information-property-list/cfbundleidentifier), the bundle identifier supports (A–Z, a–z, and 0–9), hyphens (-), and periods (.). I think we should keep it as it is instead of lowering cases. Please revert for `testBundleId` function also 🙏

**Comment by ducbm051291** [comment]
Resolved your comments 🙏  @dquangit

**Review by dquangit — APPROVED** [review]
